---
title: "Self & Peer Evaluations"
subtitle: "Stat 184 Final Project"
author: "Your Name Here"
date: now
format: pdf
---
<!--Directions
Use this RMD template to complete peer and self evaluations for your final project. Be sure to answer all prompts for each team member and yourself. You'll upload the knitted PDF (not the RMD) to the appropriate Canvas Portal.
--->


# Team Member 1

## Who are you evaluating?

Jiahao Li


## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): _9__

Justification/Examples:

I handle with the main idea and the goal of the final project. And through doing the whole project i focus on the Pearson's Chi-square test. Writing the codes for the three parts of the Pearson's Chi-square test. Also the readme document hypothesis test part and updated data for giving support.


#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): __10_

Justification/Examples:
Communicate with team numebers and upload the file in time to recieve other member's feedback for the file. Giving ideas and updated the file.Respect others idea through doing the project.



#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples:
Giving feedbacks in time to help others update the file and giving ideas for each part of the project. Enhance each part's description and make the written part easier to understand.



#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): __9_

Justification/Examples:
doing my part at time and attend the communication with other team member. Keep following the leader to do my own work.




#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): _10__

Justification/Examples:
Giving chi-square test this idea to make each part more substantial. And make the project more purposeful and academic.




### Total Score (out of 50): 48


# Team Member 2

## Who are you evaluating?

 Jizhou Cheng


## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): _10__

Justification/Examples:
Jizhou undertook the bulk of the project work, including data cleaning, generating visualizations of eye color, alignment, and gender distribution, and writing the bulk of the report.



#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): 10___

Justification/Examples:
Jizhou actively incorporate feedback from team members, ensuring that everyone is involved in the project and giving ideas and updated for the project files.



#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples:
Jizhou shows great quality works and he mainly contributes for cleaning data and the structure of the report. Spliting each part progress and writing each part's goal and showing the visualization of the data.



#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): 10___

Justification/Examples:
Jizhou keep team on task and complete his work on time. Attend the group discussion and giving idea for updating and enhancing others files.




#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): _10__

Justification/Examples:
For the citations and make readme file more complete and readable.He is the leader of the team to lead all people to sucessfully complete the works.




### Total Score (out of 50): 50


